### ISSUE TITLE
Project Management - Business Case 

### ISSUE THREAD

**Issue by ivamil** [alptium/dentist#5]

**Comment by ivamil** [comment]
Hi @valentinacupac ,

pages that I use to learn and write about Business Case are :

- https://resources.workfront.com/project-management-blog/how-to-write-a-business-case-4-steps-to-a-perfect-business-case-template

- www.nic.nhs.uk/Nic.Common/file.ashx?path...Business+Case+Template+v2+NIC

- https://www.projectmanager.com/blog/project-management/how-to-write-a-business-case

Kind regards,
Iva

**Comment by valentinajemuovic** [comment]
@ivamil, looks fine.
